defmodule Metro.Records.TailerSegment do
  @structure [
    record_descriptor_word: %Numeric{ value: Metro2.Base.fixed_length, required_length: 4 },
    record_identifier: %Alphanumeric{ value: "TRAILER", required_length: 6 },
    total_base_records: %Numeric{ required_length: 9, },
    reserved: %Alphanumeric{ required_length: 9, value: nil },
    total_status_code_df: %Numeric{ required_length: 9 },
    total_j1_segments: %Numeric{ required_length: 9 },
    total_j2_segments: %Numeric{ required_length: 9 },
    block_count: %Numeric{ required_length: 9 },
    total_satus_code_da: %Numeric{ required_length: 9 },
    total_satus_code_05: %Numeric{ required_length: 9 },
    total_satus_code_11: %Numeric{ required_length: 9 },
    total_satus_code_:13 %Numeric{ required_length: 9 },
    total_satus_code_61: %Numeric{ required_length: 9 },
    total_satus_code_62: %Numeric{ required_length: 9 },
    total_satus_code_63: %Numeric{ required_length: 9 },
    total_satus_code_64: %Numeric{ required_length: 9 },
    total_satus_code_65: %Numeric{ required_length: 9 },
    total_satus_code_71: %Numeric{ required_length: 9 },
    total_satus_code_78: %Numeric{ required_length: 9 },
    total_satus_code_80: %Numeric{ required_length: 9 },
    total_satus_code_82: %Numeric{ required_length: 9 },
    total_satus_code_83: %Numeric{ required_length: 9 },
    total_satus_code_84: %Numeric{ required_length: 9 },
    total_satus_code_88: %Numeric{ required_length: 9 },
    total_satus_code_89: %Numeric{ required_length: 9 },
    total_satus_code_93: %Numeric{ required_length: 9 },
    total_satus_code_94: %Numeric{ required_length: 9 },
    total_satus_code_95: %Numeric{ required_length: 9 },
    total_satus_code_96: %Numeric{ required_length: 9 },
    total_satus_code_97: %Numeric{ required_length: 9 },
    ecoa_code_z: %Numeric{ required_length: 9 },
    total_n1_segments: %Numeric{ required_length: 9 },
    total_k1_segments: %Numeric{ required_length: 9 },
    total_k2_segments: %Numeric{ required_length: 9 },
    total_k3_segments: %Numeric{ required_length: 9 },
    total_k4_segments: %Numeric{ required_length: 9 },
    total_l1_segments: %Numeric{ required_length: 9 },
    total_social_security_numbers: %Numeric{ required_length: 9 },
    total_social_security_numbers_in_base: %Numeric{ required_length: 9 },
    total_social_security_numbers_in_j1: %Numeric{ required_length: 9 },
    total_social_security_numbers_in_j2: %Numeric{ required_length: 9 },
    total_date_of_births: %Numeric{ required_length: 9 },
    total_date_of_births_in_base: %Numeric{ required_length: 9 },
    total_date_of_births_in_j1: %Numeric{ required_length: 9 },
    total_date_of_births_in_j2: %Numeric{ required_length: 9 },
    total_telephone_numbers: %Numeric{ required_length: 9 },
    reserved_2: %Alphanumeric{ required_length: 19, value: nil },
  ]

  def stucture, do: @structure
end
